# Generated by Django 2.2.2 on 2019-06-09 22:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('name', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('rus_name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=12, unique=True)),
                ('subscription', models.BooleanField(default=True)),
                ('photo', models.BooleanField(default=False)),
                ('basket', models.CharField(default='{"basket": []}', max_length=2000)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_changes', models.DateField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('description', models.CharField(max_length=15000)),
                ('short_description', models.CharField(max_length=120)),
                ('characteristics', models.CharField(max_length=7000)),
                ('price', models.PositiveIntegerField()),
                ('count', models.PositiveIntegerField()),
                ('len_photos', models.PositiveSmallIntegerField(default=0)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('date_changes', models.DateField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MainSite.Category')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True)),
                ('total', models.PositiveIntegerField()),
                ('goods', models.CharField(max_length=2000)),
                ('status', models.CharField(default='processing', max_length=10)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='MainSite.Profile')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
