# Generated by Django 2.2.2 on 2019-06-25 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainSite', '0003_auto_20190625_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characteristic',
            name='group',
            field=models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.PROTECT, to='MainSite.CharacteristicGroup'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='basket',
            field=models.CharField(blank=True, default='', max_length=2000),
        ),
    ]
