# Generated by Django 2.2.2 on 2019-06-10 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainSite', '0004_category_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='MainSite.Category'),
        ),
    ]
