# Generated by Django 2.2.2 on 2019-06-25 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainSite', '0004_auto_20190625_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characteristic',
            name='group',
            field=models.ForeignKey(default='other', on_delete=django.db.models.deletion.PROTECT, to='MainSite.CharacteristicGroup'),
        ),
    ]
