# Generated by Django 2.2.2 on 2019-06-10 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainSite', '0005_category_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderSpot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=300)),
                ('working_hours', models.CharField(max_length=200)),
                ('volume', models.PositiveSmallIntegerField()),
                ('state', models.CharField(default='active', max_length=10)),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='status',
            field=models.CharField(default='user', max_length=6),
        ),
        migrations.AlterField(
            model_name='profile',
            name='basket',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='order',
            name='order_spot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='MainSite.OrderSpot'),
        ),
    ]
