# Generated by Django 2.2.2 on 2019-06-12 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainSite', '0006_auto_20190610_2047'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderspot',
            options={'verbose_name': 'Пункт выдачи', 'verbose_name_plural': 'Пункты выдачи'},
        ),
        migrations.AddField(
            model_name='profile',
            name='token',
            field=models.CharField(max_length=70, null=True),
        ),
    ]
