# Generated by Django 2.2.2 on 2019-06-13 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainSite', '0010_auto_20190612_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_goods_editor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_users_editor',
            field=models.BooleanField(default=False),
        ),
    ]
