# Generated by Django 2.2.2 on 2019-06-14 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainSite', '0011_auto_20190613_1318'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='photo',
            new_name='has_photo',
        ),
        migrations.AddField(
            model_name='product',
            name='bought',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
